apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-raect
  namespace: app
spec:
  replicas: 2 # Number of frontend instances
  selector:
    matchLabels:
      app: frontend-raect
  template:
    metadata:
      labels:
        app: frontend-raect
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: frontend-raect
          image: tiangolo/react-fullstack # Replace with your actual Docker image
          ports:
            - containerPort: 80 # Expose port 80 (default HTTP)
          envFrom:
            - configMapRef:
                name: frontend-react-config
          resources:
            requests:
              memory: "256Mi" # Minimum memory allocated to the container
              cpu: "200m" # Minimum CPU allocated to the container
            limits:
              memory: "512Mi" # Maximum memory the container can use
              cpu: "500m" # Maximum CPU the container can use
